"""Purge helpers for generated HDF5 plot JPG files."""

from __future__ import annotations

from dataclasses import dataclass
import re
from pathlib import Path
from typing import Any, Iterable


@dataclass(frozen=True)
class PlotTarget:
    """Registry entry describing JPG files generated by one plot method."""

    group: str
    method: str
    filename_var_part: str
    supports_filename_suffix: bool = False

    @property
    def qualified_name(self) -> str:
        """Return the group-qualified target name."""
        return f"{self.group}.{self.method}"


@dataclass
class PurgeResult:
    """Result returned by plot purge operations."""

    target: str
    matched_paths: list[Path]
    deleted_paths: list[Path]
    cancelled: bool = False


SINGLE_TARGETS: tuple[PlotTarget, ...] = (
    PlotTarget("single", "create_mass_distance_plot_density", "mass_vs_distance_loglog"),
    PlotTarget("single", "create_vx_x_plot_density", "allstar_vx_vs_x"),
    PlotTarget("single", "create_CMD_plot_density", "L_vs_Teff_loglog"),
    PlotTarget(
        "single",
        "create_galactic_energy_angular_momentum_plot_jpg",
        "galactic_E_vs_Lz",
    ),
    PlotTarget(
        "single",
        "create_galactic_energy_angular_momentum_specific_plot_jpg",
        "galactic_E_vs_Lz_specific",
    ),
    PlotTarget(
        "single",
        "create_galactic_kinetic_energy_specific_plot_jpg",
        "galactic_KE_vs_Lz_specific",
    ),
    PlotTarget("single", "create_position_plot_jpg", "x1_vs_x2", True),
    PlotTarget("single", "create_position_plot_wide_pc_jpg", "x1_vs_x2_wide_pc"),
    PlotTarget(
        "single",
        "create_position_plot_orbital_xT_xR_wide_pc_jpg",
        "orbital_xT_vs_xR_wide_pc",
    ),
    PlotTarget(
        "single",
        "create_position_plot_orbital_xT_xL_wide_pc_jpg",
        "orbital_xT_vs_xL_wide_pc",
    ),
    PlotTarget(
        "single",
        "create_position_plot_hightlight_compact_objects_jpg",
        "x1_vs_x2_highlight_compact_objects",
        True,
    ),
    PlotTarget(
        "single",
        "create_position_plot_hightlight_compact_objects_wide_pc_jpg",
        "x1_vs_x2_highlight_compact_objects_wide_pc",
    ),
    PlotTarget("single", "create_color_CMD_jpg", "CMD"),
)

BINARY_TARGETS: tuple[PlotTarget, ...] = (
    PlotTarget("binary", "create_mass_ratio_m1_plot_density", "mass_ratio_vs_primary_mass_loglog"),
    PlotTarget(
        "binary",
        "create_mass_ratio_m1_plot_jpg_compact_object_only",
        "mass_ratio_vs_primary_mass_loglog_compact_objects_only",
    ),
    PlotTarget("binary", "create_semi_m1_plot_density", "a_vs_primary_mass_loglog"),
    PlotTarget(
        "binary",
        "create_semi_m1_plot_jpg_compact_object_only",
        "a_vs_primary_mass_loglog_compact_objects_only",
    ),
    PlotTarget("binary", "create_ebind_semi_plot_density", "ebind_vs_a_loglog"),
    PlotTarget(
        "binary",
        "create_ebind_semi_plot_jpg_compact_object_only",
        "ebind_vs_a_loglog_compact_objects_only",
    ),
    PlotTarget("binary", "create_ecc_semi_plot_density", "ecc_vs_a"),
    PlotTarget(
        "binary", "create_ecc_semi_plot_jpg_compact_object_only", "ecc_vs_a_compact_objects_only"
    ),
    PlotTarget(
        "binary",
        "create_ecc_semi_plot_jpg_compact_object_only_loglog",
        "ecc_vs_a_loglog_compact_objects_only",
    ),
    PlotTarget(
        "binary",
        "create_taugw_semi_plot_jpg_compact_object_only",
        "taugw_vs_a_compact_objects_only",
    ),
    PlotTarget("binary", "create_mtot_distance_plot_density", "mtot_vs_distance_loglog"),
    PlotTarget(
        "binary",
        "create_mtot_distance_plot_jpg_compact_object_only",
        "mtot_vs_distance_loglog_compact_objects_only",
    ),
    PlotTarget("binary", "create_semi_distance_plot_density", "a_vs_distance"),
    PlotTarget(
        "binary",
        "create_semi_distance_plot_jpg_compact_object_only",
        "a_vs_distance_compact_objects_only",
    ),
    PlotTarget("binary", "create_bin_vx_x_plot_density", "bin_vx_vs_x"),
    PlotTarget(
        "binary", "create_bin_vx_x_plot_jpg_compact_object_only", "bin_vx_vs_x_compact_objects_only"
    ),
    PlotTarget("binary", "create_bin_peri_r1r2_plot_density", "peri_vs_r1r2_loglog"),
)

PLOT_TARGETS: tuple[PlotTarget, ...] = SINGLE_TARGETS + BINARY_TARGETS

COMPOSITE_TARGETS: dict[str, tuple[str, ...]] = {
    "single": tuple(target.qualified_name for target in SINGLE_TARGETS),
    "binary": tuple(target.qualified_name for target in BINARY_TARGETS),
    "hdf5": tuple(target.qualified_name for target in PLOT_TARGETS),
    "plot_hdf5_file": tuple(target.qualified_name for target in PLOT_TARGETS),
}


class PlotPurger:
    """Find, preview, and delete HDF5 plot JPG outputs."""

    def __init__(self, config: Any) -> None:
        self.config = config

    @classmethod
    def list_targets(cls) -> list[str]:
        """Return all supported purge target names."""
        composites = sorted(COMPOSITE_TARGETS)
        concrete = sorted(target.qualified_name for target in PLOT_TARGETS)
        return composites + concrete

    def preview(
        self,
        target: str,
        simu_name: str | None = None,
        plot_dir: str | Path | None = None,
        filename_suffix: str | None = None,
    ) -> PurgeResult:
        """Return files matching a purge target without deleting them."""
        paths = self._matched_paths(target, simu_name, plot_dir, filename_suffix)
        return PurgeResult(target=target, matched_paths=paths, deleted_paths=[], cancelled=False)

    def purge(
        self,
        target: str,
        simu_name: str | None = None,
        plot_dir: str | Path | None = None,
        filename_suffix: str | None = None,
        yes: bool = False,
    ) -> PurgeResult:
        """Preview and delete files for a purge target after confirmation."""
        preview = self.preview(target, simu_name, plot_dir, filename_suffix)
        print(self.format_preview(preview.matched_paths))
        if not preview.matched_paths:
            return preview

        expected_phrase = f"delete {len(preview.matched_paths)} files"
        if not yes:
            confirmation = input(f'Type "{expected_phrase}" to confirm: ')
            if confirmation != expected_phrase:
                return PurgeResult(
                    target=target,
                    matched_paths=preview.matched_paths,
                    deleted_paths=[],
                    cancelled=True,
                )

        deleted_paths: list[Path] = []
        for path in preview.matched_paths:
            path.unlink()
            deleted_paths.append(path)

        return PurgeResult(
            target=target,
            matched_paths=preview.matched_paths,
            deleted_paths=deleted_paths,
            cancelled=False,
        )

    @staticmethod
    def format_preview(paths: Iterable[Path], limit: int = 20) -> str:
        """Format a compact path preview with head and tail for long lists."""
        path_list = list(paths)
        lines = [f"Matched {len(path_list)} files"]
        if len(path_list) <= limit:
            shown_paths = path_list
        else:
            shown_paths = path_list[:10]
        lines.extend(str(path) for path in shown_paths)
        if len(path_list) > limit:
            omitted = len(path_list) - 20
            lines.append(f"... omitted {omitted} files ...")
            lines.extend(str(path) for path in path_list[-10:])
        return "\n".join(lines)

    def _matched_paths(
        self,
        target: str,
        simu_name: str | None,
        plot_dir: str | Path | None,
        filename_suffix: str | None,
    ) -> list[Path]:
        jpg_dir = self._jpg_dir(plot_dir)
        targets = self._expand_target(target)
        prefixes = self._prefixes_for(simu_name)

        matched: set[Path] = set()
        for target_entry in targets:
            for prefix in prefixes:
                pattern = self._pattern_for(prefix, target_entry, filename_suffix)
                matched.update(
                    path
                    for path in jpg_dir.glob(pattern)
                    if self._matches_filename(path.name, prefix, target_entry, filename_suffix)
                )

        safe_paths = [path.resolve() for path in matched if self._is_safe_jpg(path, jpg_dir)]
        return sorted(safe_paths)

    def _jpg_dir(self, plot_dir: str | Path | None) -> Path:
        root = Path(plot_dir if plot_dir is not None else self.config.plot_dir).expanduser()
        return (root / "jpg").resolve()

    def _prefixes_for(self, simu_name: str | None) -> list[str]:
        prefixes = self.config.figname_prefix
        if simu_name is not None:
            return [prefixes[simu_name]]
        return list(prefixes.values())

    def _expand_target(self, target: str) -> tuple[PlotTarget, ...]:
        if target in COMPOSITE_TARGETS:
            names = COMPOSITE_TARGETS[target]
            return tuple(self._target_by_name(name) for name in names)
        return (self._target_by_name(target),)

    def _target_by_name(self, target: str) -> PlotTarget:
        matches = [
            entry for entry in PLOT_TARGETS if target in {entry.qualified_name, entry.method}
        ]
        if len(matches) == 1:
            return matches[0]
        if not matches:
            raise ValueError(f"Unknown purge target: {target}")
        raise ValueError(
            f"Ambiguous purge target: {target}; use single.{target} or binary.{target}"
        )

    def _pattern_for(self, prefix: str, target: PlotTarget, filename_suffix: str | None) -> str:
        filename_part = target.filename_var_part
        if filename_suffix is not None:
            if not target.supports_filename_suffix:
                raise ValueError(f"{target.qualified_name} does not support filename_suffix")
            suffix = filename_suffix.strip("_")
            if suffix == "*":
                filename_part = f"{filename_part}_*"
            elif suffix:
                filename_part = f"{filename_part}_{suffix}"
        return f"{prefix}output_ttot_*_{filename_part}.jpg"

    def _matches_filename(
        self, name: str, prefix: str, target: PlotTarget, filename_suffix: str | None
    ) -> bool:
        filename_part = re.escape(target.filename_var_part)
        if filename_suffix is not None:
            if not target.supports_filename_suffix:
                raise ValueError(f"{target.qualified_name} does not support filename_suffix")
            suffix = filename_suffix.strip("_")
            if suffix == "*":
                filename_part = f"{filename_part}_[^/]*"
            elif suffix:
                filename_part = f"{filename_part}_{re.escape(suffix)}"
        pattern = rf"^{re.escape(prefix)}output_ttot_[^_]+_{filename_part}\.jpg$"
        return re.match(pattern, name) is not None

    @staticmethod
    def _is_safe_jpg(path: Path, jpg_dir: Path) -> bool:
        resolved = path.resolve()
        try:
            resolved.relative_to(jpg_dir)
        except ValueError:
            return False
        return resolved.is_file() and resolved.suffix == ".jpg"
